logo: /assets/img/logo.png
title: Salil Goel, PhD
description: Assistant Professor, Geoinformatics Laboratory Department of Civil Engineering
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
